const data = {
  products: [
    {
      _id: '1',
      name: 'Bear',
      category: 'Toy',
      image: '/images/bear.jpg',
      price: 29,
      countInStock: 10,
      brand: 'bearbear',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '2',
      name: 'Bear',
      category: 'Toy',
      image: '/images/bear.jpg',
      price: 29,
      countInStock: 20,
      brand: 'bearbear',
      rating: 4.5,
      numReviews: 8,
      description: 'high quality product',
    },
    {
      _id: '3',
      name: 'Bear',
      category: 'Toy',
      image: '/images/bear.jpg',
      price: 29,
      countInStock: 0,
      brand: 'bearbear',
      rating: 4.5,
      numReviews: 5,
      description: 'high quality product',
    },
    {
      _id: '4',
      name: 'Bear',
      category: 'Toy',
      image: '/images/bear.jpg',
      price: 29,
      countInStock: 15,
      brand: 'bearbear',
      rating: 4.5,
      numReviews: 11,
      description: 'high quality product',
    },
    {
      _id: '5',
      name: 'Bear',
      category: 'Toy',
      image: '/images/bear.jpg',
      price: 29,
      countInStock: 5,
      brand: 'bearbear',
      rating: 4.5,
      numReviews: 8,
      description: 'high quality product',
    },
    {
      _id: '6',
      name: 'Bear',
      category: 'Toy',
      image: '/images/bear.jpg',
      price: 29,
      countInStock: 12,
      brand: 'bearbear',
      rating: 4.5,
      numReviews: 8,
      description: 'high quality product',
    },
    {
      _id: '7',
      name: 'Bear',
      category: 'Toy',
      image: '/images/bear.jpg',
      price: 29,
      countInStock: 12,
      brand: 'bearbear',
      rating: 4.5,
      numReviews: 8,
      description: 'high quality product',
    },
    {
      _id: '8',
      name: 'Bear',
      category: 'Toy',
      image: '/images/bear.jpg',
      price: 29,
      countInStock: 12,
      brand: 'bearbear',
      rating: 4.5,
      numReviews: 8,
      description: 'high quality product',
    },
    {
      _id: '9',
      name: 'Bear',
      category: 'Toy',
      image: '/images/bear.jpg',
      price: 29,
      countInStock: 12,
      brand: 'bearbear',
      rating: 4.5,
      numReviews: 8,
      description: 'high quality product',
    },
    {
      _id: '10',
      name: 'Bear',
      category: 'Toy',
      image: '/images/bear.jpg',
      price: 29,
      countInStock: 12,
      brand: 'bearbear',
      rating: 4.5,
      numReviews: 8,
      description: 'high quality product',
    },
    {
      _id: '11',
      name: 'Bear',
      category: 'Toy',
      image: '/images/bear.jpg',
      price: 29,
      countInStock: 12,
      brand: 'bearbear',
      rating: 4.5,
      numReviews: 8,
      description: 'high quality product',
    },
    {
      _id: '12',
      name: 'Bear',
      category: 'Toy',
      image: '/images/bear.jpg',
      price: 29,
      countInStock: 12,
      brand: 'bearbear',
      rating: 4.5,
      numReviews: 8,
      description: 'high quality product',
    },
  ],
};

export default data;
